# Generated by Django 4.2.2 on 2023-08-31 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.RemoveField(
            model_name='person',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='person',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='person',
            name='mob_num',
        ),
    ]
